# Generated by Django 5.2.8 on 2026-01-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
