# Generated by Django 5.2.8 on 2025-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default.jpg', upload_to='events/'),
        ),
    ]
