# Generated by Django 5.2.8 on 2025-12-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default.jpg', null=True, upload_to='events/'),
        ),
    ]
